ISSG4/Controllers/Backend/KlientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ISSG4.Models;
using DotNetOpenMail;
using DotNetOpenMail.SmtpAuth;
using System.Transactions;
using System.Configuration;
using System.Web.Security;
using NLog;

namespace ISSG3.Controllers.Backend
{
    [Authorize(Roles = "Administratorzy,Kolportaż")]
    public class KlientController : Controller
    {
        private Entities db = new Entities();

        Logger logger = LogManager.GetCurrentClassLogger();

        //
        // GET: /Klient/

        public ViewResult Index(int start = 0, int itemsPerPage = 20, string orderBy = "ispo_user_id", bool desc = false)
        {
            ViewBag.Count = db.Users.Count();
            ViewBag.Start = start;
            ViewBag.ItemsPerPage = itemsPerPage;
            ViewBag.OrderBy = orderBy;
            ViewBag.Desc = desc;

            return View();
        }

        //
        // GET: /Klient/GridData/?start=0&itemsPerPage=20&orderBy=ispo_user_id&desc=true

        public ActionResult GridData(int start = 0, int itemsPerPage = 20, string orderBy = "ispo_user_id", bool desc = false, string user = "")
        {
            ObjectContext objectContext = ((IObjectContextAdapter)db).ObjectContext;
            ObjectQuery<Users> users = objectContext.CreateObjectSet<Users>("Users");

            if (!string.IsNullOrWhiteSpace(user))
                users = users.Where("it.Imie like '%" + user + "%' or it.Nazwisko like '%" + user + "%' or it.Email like '%" + user + "%' or it.UserName like '%" + user + "%'");

            users = users.OrderBy("it." + orderBy + (desc ? " desc" : ""));

            Response.AppendHeader("X-Total-Row-Count", users.Count().ToString());

            return PartialView(users.Skip(start).Take(itemsPerPage));
        }

        //
        // GET: /Default5/RowData/5

        public ActionResult RowData(int id)
        {
            Users users = db.Users.Single(u => u.ispo_user_id == id);
            return PartialView("GridData", new Users[] { users });
        }

        //
        // GET: /Klient/Create

        public ActionResult Create()
        {
            //return PartialView("Edit");
            return View("Edit");
        }

        public ActionResult Przepisz(int userid)
        {

            UserAdminCreatedModel model = new UserAdminCreatedModel();

            string username = Membership.GetUser((object)userid).UserName;
            logger.Debug("Przepisywanie prenumeraty dla usera id:"+userid.ToString()+", username:"+username);

            model.username = username;
            //model.passwd = passwordreturn;
            //model.admin_email = admin_email_address;

            List<viewZamowienieJoined> zamowienia = new List<viewZamowienieJoined>();

            //pokaż prenumeraty zalogowane usera by je potem przepisać.
            using (Entities ie = new Entities())
            {
                if (User.Identity.IsAuthenticated)
                {
                    int userId = (int)Membership.GetUser().ProviderUserKey;
                    zamowienia = ie.viewZamowienieJoined.Where(m => m.issg_user_id == userId).OrderBy(m => m.ZamowienieData).ToList();
                    model.prenumeraty = zamowienia;
                }
            }

            return View(model);
        }

        //
        // POST: /Klient/Create

        [HttpPost]
        public ActionResult Create(Users users)
        {
            string imie ="-";
            string nazwisko = "-";
            string telefon= "-";
            string email;
            string login = "";

            string hash = "";
            string salt = "";
            string password = "";

            string message;

            login = users.UserName;
            email = users.UserName;
            imie = string.IsNullOrEmpty(users.Imie) == true ? "---" : users.Imie;
            nazwisko = string.IsNullOrEmpty(users.Nazwisko) == true ? "---" : users.Nazwisko;
            telefon = string.IsNullOrEmpty(users.telefon) == true ? "---" : users.telefon;
            string passwordreturn;
            
            
            //przrobić na wersję uruchamianą z db. Tam ma być jedna procedura
            // na bazie logiki związanej z issg_users_auto
            // TODO

            List<viewZamowienieJoined> zamowienia = new List<viewZamowienieJoined>();

            using (Entities db = new Entities())
            {
                //ObjectParameter op = new ObjectParameter("haslo",typeof(string));

                logger.Debug("Uruchamiam procedurę sql dodawania usera: "+login);
                
                passwordreturn = db.addUserFromAdmin(login,imie, nazwisko, telefon).Single();
               // password = op.Value.ToString();
            }

            if (!string.IsNullOrEmpty(passwordreturn))
            {
                //ukryte carbon copy dla awaryjnego przekazania hasła.
                string admin_email_address = Membership.GetUser().Email;
                logger.Debug("Mail admina dla wysłania hasło tworzonego konta: "+admin_email_address);

                logger.Debug("UserAdmin created, hasło: " + passwordreturn);
                SendPassByMailForAdminUser(login, passwordreturn, admin_email_address);
                logger.Debug("UserAdmin created, mailed");

                UserAdminCreatedModel model = new UserAdminCreatedModel();
                model.username = login;
                model.passwd = passwordreturn;
                model.admin_email = admin_email_address;

                using (Entities ie = new Entities())
                {
                    if (User.Identity.IsAuthenticated)
                    {
                        int userId = (int)Membership.GetUser().ProviderUserKey;
                        zamowienia = ie.viewZamowienieJoined.Where(m => m.issg_user_id == userId).OrderBy(m => m.ZamowienieData).ToList();
                        model.prenumeraty = zamowienia;
                    }
                }

                return View("Created",model);
            }


            //if (validateLogin(login, out message))
            //{

            //    /* generujemy hasło, oraz pasujące salt i hash */

            //    /* w transakcji należy wpisać do issg_users_auto z odpowiednią grupą. */

            //    /*issg_users_auto iua = new issg_users_auto();
            //    iua.grupa = "ISSG3Backend";
            //    iua.haslo = password;
            //    iua.salt = salt;
            //    iua.haslo = hash;
            //    iua.login = login;*/

            
            //}


            //if (ModelState.IsValid)
            //{
            //    db.Users.AddObject(users);
            //    db.SaveChanges();
            //    return PartialView("GridData", new Users[] { users });
            //}

            //return PartialView("Edit", users);
            return View("Edit", users);
        }

      

        public ActionResult Created(UserAdminCreatedModel model)
        {

            return View(model);
        }

        private bool validateLogin(string login, out string message)
        {
            message = "";

            if (login.Length < 5)
            {
                message = "Minimalna długość loginu to 5 znaków";
            }
            if (login.Length < 5 || login.Length > 224)
            {
                message = "Maksymalna długość loginu to 224 znaki";
            }

            return message.Length == 0 ? true : false;
        }

        //
        // GET: /Klient/Edit/5

        public ActionResult Edit(int id)
        {
            Users users = db.Users.Single(u => u.ispo_user_id == id);
            return PartialView(users);
        }

        //
        // POST: /Klient/Edit/5

        [HttpPost]
        public ActionResult Edit(Users users)
        {
            if (ModelState.IsValid)
            {
                ObjectContext objectContext = ((IObjectContextAdapter)db).ObjectContext;
                db.Users.Attach(users);
                objectContext.ObjectStateManager.ChangeObjectState(users, EntityState.Modified);
                db.SaveChanges();
                return PartialView("GridData", new Users[] { users });
            }

            return PartialView(users);
        }

        //
        // POST: /Klient/Delete/5

        [HttpPost]
        public void Delete(int id)
        {
            Users users = db.Users.Single(u => u.ispo_user_id == id);
            db.Users.Remove(users);
            db.SaveChanges();
        }

        public ActionResult Szczegoly(int id)
        {
            var User = db.Users.Where(m => m.ispo_user_id == id).Single();

            return PartialView(User);
        }

        public void Blokada(int id, bool blokada)
        {
            var usr = db.Users.Where(m => m.ispo_user_id == id).Single();
            usr.czy_zablokowane = (blokada ? "t" : "n" );
            usr.czy_zablokowane_kiedy = DateTime.Now;
            usr.czy_zablokowane_kto = User.Identity.Name;

            db.SaveChanges();
        }

        public ViewResult ZdarzeniaAudyt(int id)
        {
            var User = db.Users.Where(m => m.ispo_user_id == id).Single();

            return View(User);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public void SendPassByMailForAdminUser(string username, string as_newpass, string admin_email_address)
        {
            Logger logger = LogManager.GetCurrentClassLogger();
            SmtpServer smtpServer;
            AppSettingsReader apr = new AppSettingsReader();

            string ls_mailserver = apr.GetValue("MailServer", typeof(string)).ToString();
            string ls_mailaddress = apr.GetValue("MailSenderAddress", typeof(string)).ToString();

ISSG4/Views/Klient/Created.cshtml
@model ISSG4.Models.UserAdminCreatedModel
@using (Html.BeginForm())
{
    <text>
    Utworzono konto klienta w systemie.  Email z hasłem widocznym poniżej został wysłany na adres @Model.username i adres zakładającego
    @Model.admin_email
    <br/>
    <br/>
    
    </text>
    
    <table>
        <tbody>
            <tr>
                <td style="text-align: left;">
                    Login
                </td>
                <td>
                    Hasło
                </td>
            </tr>
            <tr>
                <td style="text-align: left;">@Model.username</td>
                <td>@Model.passwd</td>
            </tr>
        </tbody>
    </table>
    
    
    @* szybkie przepisanie prenumeraty dla nowoutworzonego usera *@
    <br/><br/>
    <text>
    Skopiuj prenumeratę dla nowego klienta wg wzorca z listy: <br/>
    </text>
    <table>
     <thead>
            <tr>
                @*<th>Nr</th>*@
                <th>
                    Nr zam.
                </th>
                <th>
                    Gazeta
                </th>
                <th>
                    Rodzaj prenumeraty
                </th>
                <th>
                    Ważna od
                </th>
                <th>
                    Ważna do
                </th>
                <th style="width:160px">
                </th>
            </tr>
        </thead>
     <tbody>
            @foreach (var item in Model.prenumeraty.Where(model => model.ZamowieniePozycjaWidoczna == "t"))
            {
                //Nr1++;
                <tr>
                    @*<td>@Nr1</td>*@
                    <td>@item.ZamowienieId
                    </td>
                    <td>@item.GazetaNazwa
                    </td>
                    <td>@item.ProduktNazwa
                    </td>
                    <td>@item.ZamowieniePozycjaOd.ToString("d\\/MM\\/yyyy")
                    </td>
                    <td>@item.ZamowieniePozycjaDo.ToString("d\\/MM\\/yyyy")
                    </td>
                    <td style="width:160px">
                    @{
                        string id = "Skopiuj" + item.ZamowieniePozycjaId.ToString();
                        string func_exec = "return skopiujPren(" + @item.ZamowieniePozycjaId.ToString() + ",'" + Model.username + "');";
                    }
                    <div id="@id" onclick="@func_exec">
                            <img src="/Przycisk/Skopiuj" alt="Skopiuj prenumeratę" />
                        </div>
                        @*<a href="@Url.Action("Skopiuj","Prenumerata", new { id = @item.ZamowieniePozycjaId })">
                            <img src="/Przycisk/Skopiuj" alt="Skopiuj prenumeratę" />
                        </a>*@
                    </td>
                </tr>
            }
        </tbody>
        </table>
    
    <br/><br/>
     <text>
   Prenumeraty niewidoczne w Twoim koncie:
    </text>
    <table>
     <thead>
            <tr>
                @*<th>Nr</th>*@
                <th>
                    Nr zam.
                </th>
                <th>
                    Gazeta
                </th>
                <th>
                    Rodzaj prenumeraty
                </th>
                <th>
                    Ważna od
                </th>
                <th>
                    Ważna do
                </th>
                <th style="width:160px">
                </th>
            </tr>
        </thead>
     <tbody>
            @foreach (var item in Model.prenumeraty.Where(model => model.ZamowieniePozycjaWidoczna == "n"))
            {
                //Nr1++;
                <tr>
                    @*<td>@Nr1</td>*@
                    <td>@item.ZamowienieId
                    </td>
                    <td>@item.GazetaNazwa
                    </td>
                    <td>@item.ProduktNazwa
                    </td>
                    <td>@item.ZamowieniePozycjaOd.ToString("d\\/MM\\/yyyy")
                    </td>
                    <td>@item.ZamowieniePozycjaDo.ToString("d\\/MM\\/yyyy")
                    </td>
                    <td style="width:160px">
                        <a href="@Url.Action("Skopiuj", "Prenumerata", new { id = @item.ZamowieniePozycjaId })">
                            <img src="/Przycisk/Skopiuj" alt="Skopiuj prenumeratę" />
                        </a>                       
                    </td>
                </tr>
            }
        </tbody>
        </table>
    
    
}

ISSG4/Views/Klient/Edit.cshtml
@model ISSG4.Models.Users

@using (Html.BeginForm())
{
<table>
<tbody>
<tr>
        <td  style="text-align:left;">
            Login/Email
        </td>
          <td>
          
        </td>
    </tr>

    <tr>
        <td>
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </td>
          <td>
        </td>
    </tr>

    <tr>
         <td style="text-align:left;">
            Imię
        </td>
        <td>
            Nazwisko
        </td>
    </tr>
    <tr>
         <td>
            @Html.EditorFor(model => model.Imie)
            @Html.ValidationMessageFor(model => model.Imie)
        </td>
        <td>
            @Html.EditorFor(model => model.Nazwisko)
            @Html.ValidationMessageFor(model => model.Nazwisko)
        </td>
    </tr>

        <tr>
    <td>
        Telefon
    </td>
   <td>
   </td>
   </tr>


    <tr>
    <td style="text-align:left;">
        @Html.EditorFor(model => model.telefon)
        @Html.ValidationMessageFor(model => model.telefon)
    </td>
   <td>
   </td>
   </tr>


   <tr>
    <td>

@if (ViewContext.RouteData.Values["Action"].ToString() == "Edit")
{
        <button class="editRow">Zapisz</button><button class="cancelEditRow">Anuluj</button>
}
else
{
        <button class="createRow">Utwórz</button><button class="cancelCreateRow">Anuluj</button>
}
    </td>
</tr>
</tbody>
</table>
}

ISSG4/Views/Klient/GridData.cshtml
@model IEnumerable<ISSG4.Models.Users>

@foreach (var item in Model) {
    <tr data-pkey="@item.ispo_user_id">
        <td>
            <b>@Html.DisplayFor(modelItem => item.UserName)</b><br />
            <span class="small">@Html.DisplayFor(modelItem => item.Imie) @Html.DisplayFor(modelItem => item.Nazwisko)<br />
            <a href="mailto:@item.Email">@Html.DisplayFor(modelItem => item.Email)</a></span>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nazwa_firmy)
        </td>
        <td>
            @if (item.czy_zablokowane == "t")
            {
            <span style="color: #ff0000;">Zablokowane</span><br />
            @Html.DisplayFor(modelItem => item.czy_zablokowane_kto)<br />
            @Html.DisplayFor(modelItem => item.czy_zablokowane_kiedy)
            }
            else
            {
                <text>Brak</text>
            }
        </td>
        <td class="rowControl hidden">
            @*<a href="#makeRowEditable" class="makeRowEditable">Edytuj</a> |
            <a href="#deleteRow" class="deleteRow">Usuń</a>*@
            <a href="#details" class="details">Informacje szczegołowe</a>
            <br />

            @Html.ActionLink("Zdarzenia", "Index", "KlientZdarzenia",
                                    new { userid = item.ispo_user_id.ToString() },
                                    new
                                    {
                                        title = "Zdarzenia klienta"
                                    })
            /
            @Html.ActionLink("Zmiany", "Index", "KlientAudyt",
                                    new { userid = item.ispo_user_id.ToString() },
                                    new
                                    {
                                        title = "Audyt zmian"
                                    })

            <br />


            @if (item.czy_zablokowane == "t")
            {
                <a href="#blokada" class="blokada false">Odblokuj</a>
            }
            else
            {
                <a href="#blokada" class="blokada true">Zablokuj</a>
            }

            /

            @Html.ActionLink("Przepisz pren.", "Przepisz", "Klient",
                                    new { userid = item.ispo_user_id.ToString() },
                                    new
                                    {
                                        title = "Przepisz prenumeratę."
                                    })

        </td>
    </tr>
}

ISSG4/Views/Klient/Przepisz.cshtml
@model ISSG4.Models.UserAdminCreatedModel
@using (Html.BeginForm())
{
    <text>
    Użytkownikowi <bold>@Model.username</bold> możesz tutaj skopiować prenumeratę, która wcześniej została utworzona na Twoim koncie. 
    Przy odpowiedniej pozycji kliknij Skopiuj.
    <br/>
    <br/>
    
    </text>
    
    @* szybkie przepisanie prenumeraty dla nowoutworzonego usera *@
    <br/><br/>
    <table>
     <thead>
            <tr>
                @*<th>Nr</th>*@
                <th>
                    Nr zam.
                </th>
                <th>
                    Gazeta
                </th>
                <th>
                    Rodzaj prenumeraty
                </th>
                <th>
                    Ważna od
                </th>
                <th>
                    Ważna do
                </th>
                <th style="width:160px">
                </th>
            </tr>
        </thead>
     <tbody>
            @foreach (var item in Model.prenumeraty.Where(model => model.ZamowieniePozycjaWidoczna == "t"))
            {
                //Nr1++;
                <tr>
                    @*<td>@Nr1</td>*@
                    <td>@item.ZamowienieId
                    </td>
                    <td>@item.GazetaNazwa
                    </td>
                    <td>@item.ProduktNazwa
                    </td>
                    <td>@item.ZamowieniePozycjaOd.ToString("d\\/MM\\/yyyy")
                    </td>
                    <td>@item.ZamowieniePozycjaDo.ToString("d\\/MM\\/yyyy")
                    </td>
                    <td style="width:160px">
                    @{
                        string id = "Skopiuj" + item.ZamowieniePozycjaId.ToString();
                        string func_exec = "return skopiujPren(" + @item.ZamowieniePozycjaId.ToString() + ",'" + Model.username + "');";
                    }
                    <div id="@id" onclick="@func_exec">
                            <img src="/Przycisk/Skopiuj" alt="Skopiuj prenumeratę" />
                        </div>
                        @*<a href="@Url.Action("Skopiuj","Prenumerata", new { id = @item.ZamowieniePozycjaId })">
                            <img src="/Przycisk/Skopiuj" alt="Skopiuj prenumeratę" />
                        </a>*@
                    </td>
                </tr>
            }
        </tbody>
        </table>
    
    <br/><br/>
     <text>
   Prenumeraty niewidoczne w Twoim koncie:
    </text>
    <table>
     <thead>
            <tr>
                @*<th>Nr</th>*@
                <th>
                    Nr zam.
                </th>
                <th>
                    Gazeta
                </th>
                <th>
                    Rodzaj prenumeraty
                </th>
                <th>
                    Ważna od
                </th>
                <th>
                    Ważna do
                </th>
                <th style="width:160px">
                </th>
            </tr>
        </thead>
     <tbody>
            @foreach (var item in Model.prenumeraty.Where(model => model.ZamowieniePozycjaWidoczna == "n"))
            {
                //Nr1++;
                <tr>
                    @*<td>@Nr1</td>*@
                    <td>@item.ZamowienieId
                    </td>
                    <td>@item.GazetaNazwa
                    </td>
                    <td>@item.ProduktNazwa
                    </td>
                    <td>@item.ZamowieniePozycjaOd.ToString("d\\/MM\\/yyyy")
                    </td>
                    <td>@item.ZamowieniePozycjaDo.ToString("d\\/MM\\/yyyy")
                    </td>
                    <td style="width:160px">
                        <a href="@Url.Action("Skopiuj", "Prenumerata", new { id = @item.ZamowieniePozycjaId })">
                            <img src="/Przycisk/Skopiuj" alt="Skopiuj prenumeratę" />
                        </a>                       
                    </td>
                </tr>
            }
        </tbody>
        </table>
    
    
}

ISSG4/Views/Klient/Szczegoly.cshtml
@model ISSG4.Models.Users

<div style="width: 600px;">

<h2>@Html.DisplayFor(model => model.UserName)</h2>

<style>
    #userInfo { width: 100%; }
    #userInfo td { background-color: #fff; vertical-align: top; width: 50%; }
</style>

<table id="userInfo">
<tr>

@*Pierwsza kolumna*@
<td>

    <div class="display-field">
        <span style="font-size: 14pt; font-weight: bold;">@Html.DisplayFor(model => model.Imie) @Html.DisplayFor(model => model.Nazwisko)</span>
    </div>

    <div class="display-field">
        Email: <a href="mailto:@Html.DisplayFor(model => model.Email)">@Html.DisplayFor(model => model.Email)</a>
    </div>

    <div class="display-field">
        Telefon: @Html.DisplayFor(model => model.telefon)
    </div>

    <h3>Adres</h3>

    <div class="display-field">
        @Html.DisplayFor(model => model.ulica) @Html.DisplayFor(model => model.budynek) / @Html.DisplayFor(model => model.mieszkanie)<br />
        @Html.DisplayFor(model => model.Kod) @Html.DisplayFor(model => model.Miejscowosc)<br />
        @Html.DisplayFor(model => model.kraj)
    </div>

    <h3>Adres do korespondencji</h3>
    <div class="display-field">
        @Html.DisplayFor(model => model.koresp1)
        @Html.DisplayFor(model => model.koresp2)
        @Html.DisplayFor(model => model.koresp3)
        @Html.DisplayFor(model => model.koresp4)
    </div>

    <h3>Systemowe</h3>
@*    <div class="display-field">
        Grupa: @Html.DisplayFor(model => model.Grupa_id)
    </div>*@
    <div class="display-field">
        Utworzono: @Html.DisplayFor(model => model.add_time)
    </div>

    <div class="display-field">
        Blokada: 
        @if (Model.czy_zablokowane == "t")
        {
            <text>tak<br />
            Kto zablokował: @Html.DisplayFor(model => model.czy_zablokowane_kto)<br />
            Kiedy zablokowane: @Html.DisplayFor(model => model.czy_zablokowane_kiedy)
            </text>
        }
        else
        {
            <text>nie</text>
        }
    </div>

</td>

@*Druga kolumna*@
<td>

    <h3>Dane firmowe</h3>

    <div class="display-field">
        Konto firmowe:
        @if (Model.czy_firma.GetValueOrDefault(false))
        {
            <text>tak</text>
        }
        else
        {
            <text>nie</text>
        }
    </div>
    
    <div class="display-field">
        Nazwa firmy: @Html.DisplayFor(model => model.nazwa_firmy)
    </div>
    
    <div class="display-field">
        NIP: @Html.DisplayFor(model => model.nip)
    </div>

    

    @*<div class="display-label">kod_external</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.kod_external)
    </div>*@

    <div class="display-field">
        Posiada kredyt: 
        @if (Model.klient_czy_kredyt == "t")
        {
            <text>tak</text>
        }
        else
        {
            <text>nie</text>
        }
    </div>

    <div class="display-field">
        Faktura VAT: 
        @if (Model.czy_faktura.GetValueOrDefault(false))
        {
            <text>tak</text>
        }
        else
        {
            <text>nie</text>
        }
    </div>

@*    <div class="display-label">ag_id</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ag_id)
    </div>*@

    

@*    <div class="display-label">kod_external_2</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.kod_external_2)
    </div>

    <div class="display-label">kod_external_3</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.kod_external_3)
    </div>

    <div class="display-label">aw_user_id</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.aw_user_id)
    </div>*@

    <h3>Zgody</h3>

    <div class="display-field">
        Zgoda na przetwarzanie danych: 
        @if (Model.czy_zgoda_przetwarzanie.GetValueOrDefault(false))
        {
            <text>tak</text>
        }
        else
        {
            <text>nie</text>
        }
    </div>

    <div class="display-field">
        Zgoda na przesyłanie reklam:
        @if (Model.czy_zgoda_reklamy.GetValueOrDefault(false))
        {
            <text>tak</text>
        }
        else
        {
            <text>nie</text>
        }
    </div>

@*    <div class="display-label">add_system</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.add_system)
    </div>*@

</td>

</tr>
</table>





@*<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ispo_user_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

<p style="text-align: right;">
    <input style="width: 120px;" type="button" value="OK" class="oknoOK" />
</p>

</div>